package com.cryo.db;

import com.cryo.entities.instructions.Instruction;
import com.cryo.entities.instructions.impl.*;

import java.util.HashMap;

public enum InstructionDefinitions {
	PUSH_INT(79, true, false, false, null, null, PushInstruction.class),
	PUSH_STRING(57, true, false, false, null, null, PushInstruction.class),
	PUSH_LONG(633, true, false, false, null, null, PushInstruction.class),
	STORE_INT(168, true, false, false, null, null, StoreVariableInstruction.class),
	STRUCT_PARAM(594, false, true, false, null, null),
	HOOK_MOUSE_PRESS(881, false, false, true, null, null),
	INSTR6393(486, false, false, true, null, null),
	IF_SETONMOUSEOVER(753, false, false, true, null, null),
	INSTR6253(532, false, false, true, null, null),
	INSTR6248(730, false, false, true, null, null),
	STORE_STRING(356, true, false, false, null, null, StoreVariableInstruction.class),
	STORE_VARC_STRING(21, true, false, false, null, null, StoreVarInstruction.class),
	STORE_VARPBIT(371, true, false, false, null, null, StoreVarInstruction.class),
	STORE_LONG(987, true, false, false, null, null, StoreVariableInstruction.class),
	LOAD_INT(500, true, false, false, null, null, LoadVariableInstruction.class),
	ARRAY_NEW(235, true, false, false, null, null),
	LOAD_STRING(799, true, false, false, null, null, LoadVariableInstruction.class),
	LOAD_VARC_STRING(700, true, false, false, null, null, LoadVarInstruction.class),
	LOAD_VARP(154, true, false, false, null, null, LoadVarInstruction.class),
	LOAD_VARPBIT(408, true, false, false, null, null, LoadVarInstruction.class),
	POP_STRING(354, false, false, false, null, null),
	POP_INT(492, false, false, false, null, null),
	LOAD_LONG(473, true, false, false, null, null),
	ADD(279, false, false, false, null, null, MathsInstruction.class),
	SUBTRACT(130, false, false, false, null, null, MathsInstruction.class),
	DIVIDE(56, false, false, false, null, null, MathsInstruction.class),
	MULTIPLY(367, false, false, false, null, null, MathsInstruction.class),
	RETURN(184, false, false, false, null, null, ReturnInstruction.class),
	ARRAY_LOAD(859, true, false, false, null, null, LoadArrayInstruction.class),
	ARRAY_STORE(116, true, false, false, null, null, StoreArrayInstruction.class),
	MERGE_STRINGS(531, true, false, false, null, null),
	LOAD_VARC(311, true, false, false, null, null, LoadVarInstruction.class),
	STORE_VARC(510, true, false, false, null, null, StoreVarInstruction.class),
	CALL_CS2(902, true, false, false, null, null, CallScriptInstruction.class),
	INT_LT(566, true, false, false, null, null, IfStatementInstruction.class),
	INT_GT(939, true, false, false, null, null, IfStatementInstruction.class),
	GOTO(123, true, false, false, null, null, NoInstruction.class),
	INT_EQ(933, true, false, false, null, null, IfStatementInstruction.class),
	LONG_NE(908, true, false, false, null, null, IfStatementInstruction.class),
	LONG_EQ(381, true, false, false, null, null, IfStatementInstruction.class),
	LONG_LT(597, true, false, false, null, null, IfStatementInstruction.class),
	LONG_GT(237, true, false, false, null, null, IfStatementInstruction.class),
	LONG_LE(465, true, false, false, null, null, IfStatementInstruction.class),
	LONG_GE(142, true, false, false, null, null, IfStatementInstruction.class),
	INT_GE(319, true, false, false, null, null, IfStatementInstruction.class),
	INSTR6091(1, false, false, false, null, null),
	INSTR6687(457, false, false, false, null, null),
	INSTR6092(665, false, false, false, null, null),
	CC_SETONMOUSEOVER(207, false, false, false, null, null),
	INSTR6224(705, false, false, false, null, null),
	INSTR6499(392, false, false, false, null, null),
	INSTR5957(158, false, false, false, null, null),
	INSTR6246(550, false, false, true, null, null),
	LOAD_CLAN_SETTING_VAR_LONG(83, true, false, false, null, null, LoadVarInstruction.class),
	INT_LE(670, true, false, false, null, null, IfStatementInstruction.class),
	INT_NE(693, true, false, false, null, null, IfStatementInstruction.class),
	SWITCH(377, true, false, false, null, null, SwitchInstruction.class),
	ENUM(540, false, false, false, null, null, EnumInstruction.class),
	SEND_MESSAGE(471, false, false, false, new String[]{"s"}, null),
	TO_STRING(688, false, false, false, new String[]{"i"}, "string", CustomInstruction.class),
	ACTIVECLANSETTINGS_GETAFFINEDCOUNT(706, false, false, false, null, "int"),
	ACTIVECLANSETTINGS_GETCLANNAME(815, false, false, false, null, "string"),
	LOAD_CLAN_SETTING_VAR_STRING(910, true, false, false, null, null, LoadVarInstruction.class),
	ACTIVECLANSETTINGS_GETSORTEDAFFINEDSLOT(956, false, false, false, new String[]{"i"}, "int"),
	SET_GENDER(325, false, false, false, new String[]{"i"}, null),
	SET_ITEM(925, false, false, false, new String[]{"i", "i"}, null),
	CC_SETMAXLINES(77, false, false, false, new String[]{"i"}, null),
	FC_GETCHATUSERWORLD(587, false, false, false, new String[]{"i"}, "int"),
	DETAILGET_CURRENTTOOLKIT(725, false, false, false, null, "int"),
	INSTR6305(422, false, false, false, null, "int"),
	INSTR6632(288, false, false, false, new String[]{"i", "i"}, null),
	INSTR6803_1(233, false, false, false, new String[]{"i", "i"}, null),
	USERDETAIL_LOBBY_CCEXPIRY(679, false, false, false, null, "int"),
	FRIEND_GETNAMES(252, false, false, false, new String[]{"i"}, "string,string"),
	INSTR6663(893, false, false, false, null, null),
	INSTR6108(868, false, false, false, null, null),
	INSTR6684(483, false, false, false, null, null),
	INSTR6631(662, false, false, false, new String[]{"i"}, null),
	INSTR6308(84, false, false, false, new String[]{"i"}, null),
	CHECK_JAVA_VERSION(826, false, false, false, null, "int"),
	CC_SETCLICKMASK(924, false, false, false, new String[]{"i"}, null),
	DETAILSET_STEREO(383, false, false, false, new String[]{"i"}, null),
	DETAILSET_CHARACTER_SHADOWS(226, false, false, false, new String[]{"i"}, null),
	DETAILSET_CPU(90, false, false, false, new String[]{"i"}, null),
	DETAILSET_MAXSCREENSIZE(568, false, false, false, new String[]{"i"}, null),
	DETAILSET_SKYBOX(332, false, false, false, new String[]{"i"}, null),
	DETAILSET_PARTICLES(703, false, false, false, new String[]{"i"}, null),
	DETAILCANSET_SKYBOXES(53, false, false, false, null, "int"),
	DETAILCANSET_MAXSCREENSIZE(921, false, false, false, null, "int"),
	DETAILCANMOD_MAXSCREENSIZE(446, false, false, false, null, "int"),
	DETAILGET_BLOOM(752, false, false, false, null, "int"),
	DETAILCANMOD_SKYBOXES(821, false, false, false, null, "int"),
	DETAILCANSET_PARTICLES(876, false, false, false, null, "int"),
	DETAILGET_SKYBOXES(581, false, false, false, null, "int"),
	DETAILCANMOD_PARTICLES(803, false, false, false, null, "int"),
	DETAILSET_GROUND_BLENDING(464, false, false, false, new String[]{"i"}, null),
	DETAILGET_CPU(804, false, false, false, null, "int"),
	DETAILSET_LIGHTDETAIL_HIGH(281, false, false, false, new String[]{"i"}, null),
	INSTR5975(712, false, false, false, null, "int"),
	DETAILSET_BLOOM(564, false, false, false, new String[]{"i"}, null),
	DETAILSET_SCENERY_SHADOWS(270, false, false, false, new String[]{"i"}, null),
	DETAILGET_WATERDETAIL_HIGH(487, false, false, false, null, "int"),
	FRIEND_GETWORLDFLAGS(562, false, false, false, new String[]{"i"}, "int"),
	DETAILGET_LIGHT_DETAIL(891, false, false, false, null, "int"),
	DETAILGET_TEXTURES(418, false, false, false, null, "int"),
	INSTR6617(674, false, false, false, null, "int,int"),
	INSTR6674(269, false, false, false, new String[]{"i"}, null),
	INSTR6065(878, false, false, false, new String[]{"i", "i"}, null),
	DETAILGET_BRIGHTNESS(848, false, false, false, null, "int"),
	FRIEND_IS_REFERRER(656, false, false, false, new String[]{"i"}, "int"),
	IGNORE_GETNAME_UNFILTERED(37, false, false, false, new String[]{"i"}, "string"),
	MEC_TEXT(985, false, false, false, new String[]{"i"}, "string"),
	DETAILGET_MONO_STEREO(26, false, false, false, null, "int"),
	DETAILGET_SCENERY_SHADOWS(390, false, false, false, null, "int"),
	DETAILGET_FOG(193, false, false, false, null, "int"),
	DETAILGET_DEFAULT_ANTIALIASING(458, false, false, false, null, "int"),
	DETAILGET_TOOLKIT(734, false, false, false, null, "int"),
	IF_GETMODELTYPE(864, false, false, false, new String[]{"ic"}, "int"),
	INSTR6074(975, false, false, false, new String[]{"i", "i"}, "int"),
	INSTR6607(386, false, false, false, new String[]{"i"}, null),
	INSTR6616(788, false, false, false, null, "int,int"),
	INSTR6613(830, false, false, false, null, "int"),
	INSTR6849(560, false, false, false, null, "int,int"),
	DETAILGET_CHARACTER_SHADOWS(646, false, false, false, null, "int"),
	DETAILSET_FLICKERING_EFFECTS(71, false, false, false, new String[]{"i"}, null),
	DETAILSET_TEXTURES(218, false, false, false, new String[]{"i"}, null),
	INSTR6204(273, false, false, false, null, null),
	INSTR6712(569, false, false, false, null, "int"),
	USERDETAIL_LOBBY_RECOVERYDAY(379, false, false, false, null, "int"),
	USERDETAIL_LOBBY_LASTLOGINDAY(236, false, false, false, null, "int"),
	IF_GETUSEONNAME(996, false, false, false, new String[]{"ic"}, "string"),
	INSTR6628(641, false, false, false, new String[]{"i", "i"}, null),
	INSTR6838(766, false, false, false, new String[]{"i"}, "int"),
	INSTR6620(923, false, false, false, new String[]{"i"}, "int"),
	SETUP_MESSAGEBOX(211, false, false, false, new String[]{"i", "i", "i", "i", "i", "i", "i", "i", "i", "i", "i"}, null),
	INV_TOTALCAT(192, false, false, false, new String[]{"i", "i"}, "int"),
	INSTR6097(423, false, false, false, null, "int"),
	INSTR6150(3, false, false, false, null, "int"),
	FC_KICKUSER(421, false, false, false, new String[]{"s"}, null),
	FRIEND_GETRANK(732, false, false, false, new String[]{"i"}, "int"),
	INSTR6599(711, false, false, false, new String[]{"s", "i"}, "int"),
	FRIEND_SETRANK(647, false, false, false, new String[]{"s", "i"}, null),
	DETAILSET_BRIGHTNESS(849, false, false, false, new String[]{"i"}, null),
	INSTR6612(16, false, false, false, null, "int,int"),
	DETAILGET_IDLE_ANIMATIONS(794, false, false, false, null, "int"),
	DETAILSET_IDLE_ANIMATIONS(553, false, false, false, new String[]{"i"}, null),
	DETAILSET_FOG(685, false, false, false, new String[]{"i"}, null),
	INSTR6858(773, false, false, false, null, null),
	FROMBILLING(655, false, false, false, null, "int"),
	CC_SETALPHA_1(209, false, false, false, new String[]{"i"}, null),
	INSTR6410(672, false, false, false, null, null),
	INSTR6207(518, false, false, false, new String[]{"ic", "i", "i"}, null),
	SEND_VERIFY_EMAIL_PACKET(654, false, false, false, new String[]{"s"}, null),
	INSTR6737(659, false, false, false, new String[]{"i"}, null),
	IF_SETLINEDIRECTION(760, false, false, false, new String[]{"ic", "i"}, null),
	DETAILGET_FLICKERING_EFFECTS(585, false, false, false, null, "int"),
	DETAILGET_GROUND_DECOR(268, false, false, false, null, "int"),
	DETAILSET_GROUND_DECOR(372, false, false, false, new String[]{"i"}, null),
	DETAILSET_WATERDETAIL_HIGH(232, false, false, false, new String[]{"i"}, null),
	INSTR6639(785, false, false, false, new String[]{"i", "i"}, "int"),
	DETAILSET_ANTIALIASING_DEFAULT(380, false, false, false, new String[]{"i"}, null),
	INSTR6680(507, false, false, false, null, null),
	CC_SETALPHA_2(209, false, false, false, new String[]{"i"}, null),
	DETAILGET_REMOVE_ROOFS(983, false, false, false, null, "int"),
	INSTR6609(484, false, false, false, new String[]{"i"}, null),
	INSTR5954(419, false, false, false, null, "int"),
	INSTR6643(691, false, false, false, null, "int"),
	INSTR6225(961, false, false, false, null, "int"),
	CONTAINER_TOTAL_PARAM(696, false, false, false, new String[]{"i", "i"}, "int"),
	IF_SETUSEOPTIONSTRING(583, false, false, false, new String[]{"ic", "s"}, null),
	INSTR6404(596, false, false, false, new String[]{"i"}, "int,int"),
	INSTR6745(348, false, false, false, new String[]{"i"}, null),
	INSTR6645(818, false, false, false, new String[]{"i"}, null),
	INSTR6406(617, false, false, false, null, "int"),
	INSTR6938(782, false, false, false, null, "int"),
	INSTR6752(817, false, false, false, new String[]{"i"}, null),
	PROFILE_CPU(930, false, false, false, null, "int"),
	INSTR6476(576, false, false, false, null, null),
	INSTR6647(649, false, false, false, new String[]{"i"}, null),
	USERDETAIL_DOB(407, false, false, false, null, "int"),
	SEND_SIGNUP_FORM_PACKET(686, false, false, false, new String[]{"s", "s", "i", "i"}, null),
	DETAILSET_REMOVEROOFS_OPTION_OVERRIDE(992, false, false, false, new String[]{"i"}, null),
	INSTR6589(303, false, false, false, null, "int"),
	INSTR6720(917, false, false, false, null, "int"),
	USERDETAIL_LOBBY_UNREADMESSAGES(241, false, false, false, null, "int"),
	USERDETAIL_LOBBY_LASTLOGINADDRESS(78, false, false, false, null, "string"),
	INSTR6867(106, false, false, false, null, "int"),
	INSTR6829(915, false, false, false, null, "int,int,string,int,string,int,int,string"),
	INSTR6227(212, false, false, false, null, "int,int,string,int,string,int,int,string"),
	INSTR6671(775, false, false, false, null, "int", SimpleInstruction.class),
	INSTR6101(44, false, false, false, null, "int"),
	INSTR6709(945, false, false, false, null, "int"),
	INSTR6630(969, false, false, false, null, "int", SimpleInstruction.class),
	INSTR6642(885, false, false, false, null, null),
	USERDETAIL_LOBBY_EMAILSTATUS(54, false, false, false, null, "int"),
	FORMAT_DATETIME_FROM_MINUTES(339, false, false, false, new String[]{"i"}, "string"),
	FRIEND_GETWORLDNAME(767, false, false, false, new String[]{"i"}, "string"),
	INSTR6439(410, false, false, false, new String[]{"i"}, null),
	INSTR6611(726, false, false, false, new String[]{"i"}, "string"),
	INSTR6700(9, false, false, false, null, "int"),
	INSTR6857(312, false, false, false, null, null),
	USERDETAIL_LOBBY_MEMBERSHIP(148, false, false, false, null, "int,int,int"),
	INSTR6090(441, false, false, false, new String[]{"i"}, null),
	IGNORE_GETNAMES(284, false, false, false, new String[]{"i"}, "string,string"),
	WORLDLIST_PINGWORLDS(678, false, false, false, new String[]{"i"}, null),
	INSTR6610(397, false, false, false, new String[]{"i"}, "int"),
	USERDETAIL_LOBBY_PLAYAGE(393, false, false, false, null, "int"),
	INSTR6803_2(233, false, false, false, null, "int"),
	AUTOSETUP_SETHIGH(398, false, false, false, null, null),
	INSTR6210(499, false, false, false, new String[]{"ic"}, null),
	INSTR6808(296, false, false, false, new String[]{"i", "i", "i", "i"}, null),
	PLAYERMOD(81, false, false, false, null, "int"),
	INSTR6702(742, false, false, false, null, "int"),
	INSTR6416(477, false, false, false, null, null),
	INSTR6922(261, false, false, false, new String[]{"i", "i"}, null),
	DETAILCANSET_RENDERER(616, false, false, false, new String[]{"i"}, "int"),
	AUTOSETUP_SETMEDIUM(837, false, false, false, null, null),
	FC_GETCHATUSERWORLDNAME(943, false, false, false, new String[]{"i"}, "string"),
	IGNORE_ADD_TEMP(954, false, false, false, new String[]{"s"}, null),
	CHAT_SENDABUSEREPORT(257, false, false, false, new String[]{"s", "s", "i", "i"}, null),
	INSTR6323(92, false, false, false, null, "int"),
	DETAILCANMOD_TOOLKIT(850, false, false, false, null, "int"),
	INSTR6653(716, false, false, false, null, null),
	INSTR6852(1005, false, false, false, null, "int,int"),
	INSTR6784(42, false, false, false, null, "int"),
	INSTR6775(737, false, false, false, null, "int"),
	AUTOSETUP_SETLOW(225, false, false, false, null, null),
	AUTOSETUP_SETMIN(955, false, false, false, null, null),
	CC_GETUSEONNAME(125, false, false, false, null, "string"),
	IF_SETSPRITESCALE(527, false, false, false, new String[]{"ic", "i"}, null),
	INSTR6162(99, false, false, false, new String[]{"i", "i", "i", "i"}, null),
	INSTR6675(570, false, false, false, new String[]{"i", "i", "i", "i"}, null),
	RANDOM_INCLUSIVE(851, false, false, false, new String[]{"i"}, "int"),
	INSTR6711(391, false, false, false, null, "int,int"),
	BASE_COLOR(156, false, false, false, new String[]{"i", "i"}, null),
	BASE_IDKIT(613, false, false, false, new String[]{"i", "i"}, null),
	GET_COL_TAG(874, false, false, false, new String[]{"i"}, "string"),
	FC_GETCHATMINKICK(346, false, false, false, null, "int"),
	IF_OPENSUBCLIENT(360, false, false, false, new String[]{"i", "i"}, null),
	IF_GETOPTIONNAME(164, false, false, false, new String[]{"ic", "i"}, "string"),
	DETAILGET_GRAPHICS(952, false, false, false, null, "int"),
	IF_SETMAXTEXTLINES(432, false, false, false, new String[]{"ic", "i"}, null),
	INSTR6212(603, false, false, false, new String[]{"i"}, "int,int"),
	INSTR6697(362, false, false, false, null, null),
	ITEM_MINIMENU_COLOUR(213, false, false, false, new String[]{"i"}, "int"),
	DETAILGET_MAXSCREENSIZE(714, false, false, false, null, "int"),
	ACTIVECLANSETTINGS_GETRANKTALK(91, false, false, false, null, "int"),
	ACTIVECLANSETTINGS_GETAFFINEDDISPLAYNAME(541, false, false, false, new String[]{"i"}, "string"),
	FC_GETCHATRANK(854, false, false, false, null, "int"),
	INSTR6627(722, false, false, false, new String[]{"i"}, null),
	ACTIVECLANSETTINGS_GETALLOWUNAFFINED(843, false, false, false, null, "int"),
	IF_SETTARGETCURSOR(896, false, false, false, new String[]{"ic", "i", "i"}, null),
	IF_SETVFLIP(503, false, false, false, new String[]{"ic", "i"}, null),
	CLANFORUMQFC_TOSTRING(454, false, false, false, new String[]{"l"}, "string"),
	APPEND_NUM(310, false, false, false, new String[]{"s", "i"}, "string"),
	INSTR6821(17, false, false, false, new String[]{"i"}, "int,int,int"),
	GETCLIPBOARD(853, false, false, false, null, "string"),
	ACTIVECLANSETTINGS_GETCURRENTOWNER_SLOT(962, false, false, false, null, "int"),
	FC_ISSELF(802, false, false, false, new String[]{"i"}, "int"),
	INSTR6716(759, false, false, false, null, "int"),
	RESUME_CLANFORUMQFCDIALOG(101, false, false, false, new String[]{"s"}, null),
	IF_SETOPCURSOR(122, false, false, false, new String[]{"ic", "i", "i"}, null),
	SOUND_SYNTH(2, false, false, false, new String[]{"i", "i", "i"}, null),
	CHAT_SETFILTER(424, false, false, false, new String[]{"i", "i", "i"}, null),
	FRIEND_GETWORLD(51, false, false, false, new String[]{"i"}, "int"),
	ACTIVECLANCHANNEL_GETSORTEDUSERSLOT(5, false, false, false, new String[]{"i"}, "int"),
	FC_GETDISPLAYNAME(699, false, false, false, new String[]{"i"}, "string"),
	INSTR6792(47, false, false, false, new String[]{"i", "i", "i", "i"}, null),
	RESUME_STRINGDIALOG(4, false, false, false, new String[]{"s"}, null),
	CC_SETGRAPHIC(415, false, false, false, new String[]{"i"}, null),
	IF_SETSCROLLSIZE(628, false, false, false, new String[]{"i", "i", "i"}, null),
	INSTR6648(577, false, false, false, new String[]{"s", "s", "i"}, null),
	STRING_LENGTH(247, false, false, false, new String[]{"s"}, "int", CustomInstruction.class),
	IF_SETGRAPHIC(529, false, false, false, new String[]{"ic", "i"}, null, SimpleInstruction.class),
	INSTR6202(946, false, false, false, new String[]{"i"}, "int"),
	INV_SIZE(157, false, false, false, new String[]{"ic"}, "int"),
	CC_SETHFLIP(185, false, false, false, new String[]{"i"}, null),
	CHAT_GETFILTER_PUBLIC(860, false, false, false, null, "int"),
	CHAT_GETFILTER_TRADE(839, false, false, false, null, "int"),
	INSTR6764(745, false, false, false, new String[]{"i", "i"}, null),
	INSTR6252(179, false, false, false, null, null),
	QC_GETNAME(927, false, false, false, new String[]{"i"}, "string"),
	IF_GETSCROLLWIDTH(496, false, false, false, new String[]{"ic"}, "int"),
	IF_GETSCROLLX(932, false, false, false, new String[]{"ic"}, "int"),
	CC_DELETE(981, false, false, false, null, null, SimpleInstruction.class),
	INSTR6594(795, false, false, false, new String[]{"i"}, "int"),
	IF_GETOFFSETY(463, false, false, false, new String[]{"ic"}, "int"),
	INSTR6214(899, false, false, false, new String[]{"ic", "i", "i"}, null),
	INSTR6030(988, false, false, false, new String[]{"i", "i"}, "int"),
	QC_GETMESSAGE(604, false, false, false, new String[]{"i", "i"}, "int"),
	CHAR_TOUPPERCASE(153, false, false, false, new String[]{"i"}, "int"),
	QC_SETMESSAGE(187, false, false, false, new String[]{"i"}, null),
	QC_SENDPUBLICMESSAGE(329, false, false, false, null, null),
	QC_SENDPRIVATEMESSAGE(909, false, false, false, new String[]{"s"}, null),
	QC_SENDFRIENDSCHATMESSAGE(922, false, false, false, null, null),
	QC_SENDCLANCHATMESSAGE(285, false, false, false, null, null),
	QC_SENDGUESTCLANCHATMESSAGE(663, false, false, false, null, null),
	INSTR6596(109, false, false, false, new String[]{"i", "i"}, null),
	INSTR6597(217, false, false, false, new String[]{"i", "i"}, null),
	QC_GETSUBHOTKEY(713, false, false, false, new String[]{"i", "i"}, "int"),
	INSTR6595(324, false, false, false, new String[]{"i", "i"}, "int"),
	INSTR6581(10, false, false, false, new String[]{"i"}, "int"),
	INSTR6657(6, false, false, false, new String[]{"i", "i", "i", "i", "i", "i", "i", "i", "i", "i", "i", "i"}, null),
	IF_SETPOSITION(937, false, false, false, new String[]{"ic", "i", "i", "i", "i"}, null),
	IF_SETSIZE(982, false, false, false, new String[]{"ic", "i", "i", "i", "i"}, null),
	IF_SETTEXTFONT(85, false, false, false, new String[]{"ic", "i"}, null),
	IF_SETHIDE(590, false, false, false, new String[]{"ic", "bool"}, null, SimpleInstruction.class),
	INV_TOTAL(485, false, false, false, new String[]{"i", "i"}, "int", SimpleInstruction.class),
	CC_DELETEALL(572, false, false, false, new String[]{"ic"}, null, SimpleInstruction.class),
	PARAMHEIGHT(469, false, false, false, new String[]{"s", "i", "i"}, "int"),
	CC_SETTRANS(320, false, false, false, new String[]{"i"}, null, SimpleInstruction.class),
	INSTR6823(8, false, false, false, null, null),
	CC_SETITEM(13, false, false, false, new String[]{"i", "i"}, null),
	CONTAINER_FREE_SPACE(20, false, false, false, new String[]{"i"}, "int"),
	ITEM_WEARPOS(22, false, false, false, new String[]{"i"}, "int"),
	INSTR6650(567, false, false, false, new String[]{"i", "i"}, null),
	PARAWIDTH(43, false, false, false, new String[]{"s", "i", "i"}, "int"),
	INSTR6069(661, false, false, false, new String[]{"i", "i"}, "int"),
	INSTR6651(46, false, false, false, new String[]{"i", "i", "i", "i", "i", "i", "i"}, null),
	INSTR6277(38, false, false, false, new String[]{"ic"}, "int"),
	ESCAPE(49, false, false, false, new String[]{"s"}, "string"),
	INSTR6661(61, false, false, false, new String[]{"i", "ic"}, "int"),
	INSTR6676(68, false, false, false, new String[]{"i", "ic"}, null),
	INSTR6879(72, false, false, false, new String[]{"ic", "i", "i"}, null),
	CLIENT_CLOCK(80, false, false, false, null, "int", SimpleInstruction.class),
	ITEM_CERT(94, false, false, false, new String[]{"i"}, "int"),
	INSTR6279(96, false, false, false, new String[]{"ic"}, "int"),
	CC_SETTEXTSHADOW(103, false, false, false, new String[]{"i"}, null),
	SUBSTRING(108, false, false, false, new String[]{"s", "i", "i"}, "string"),
	IF_ISOPEN(888, false, false, false, new String[]{"i"}, "int"),
	CC_SETHIDE(112, false, false, false, new String[]{"i"}, null),
	CC_CREATE(113, false, false, false, new String[]{"i", "i", "i"}, null),
	RESUME_COUNTDIALOG(117, false, false, false, new String[]{"s"}, null),
	ACTIVECLANCHANNEL_FIND_LISTENED(884, false, false, false, null, "int"),
	INSTR6288(997, false, false, false, new String[]{"i"}, "int,int"),
	MAX(750, false, false, false, new String[]{"i", "i"}, "int"),
	MIN(538, false, false, false, new String[]{"i", "i"}, "int"),
	SCALE(277, false, false, false, new String[]{"i", "i", "i"}, "int", SimpleInstruction.class),
	INSTR6601(227, false, false, false, null, null),
	CHAR_TOLOWERCASE(977, false, false, false, new String[]{"i"}, "int"),
	SET_CHAT_TYPE(118, false, false, false, new String[]{"i"}, null),
	SET_BIT(119, false, false, false, new String[]{"i", "i"}, "int"),
	IF_GETLAYER(135, false, false, false, new String[]{"ic"}, "int", SimpleInstruction.class),
	IF_GETOFFSETX(721, false, false, false, new String[]{"ic"}, "int"),
	IF_SETITEM(388, false, false, false, new String[]{"ic", "i", "i"}, null),
	INSTR6621(676, false, false, false, null, "int"),
	IF_SETALPHA(368, false, false, false, new String[]{"ic", "i"}, null),
	IF_SETTEXTALIGN(741, false, false, false, new String[]{"ic", "i", "i", "i"}, null),
	INSTR6598(349, false, false, false, new String[]{"i", "i", "i"}, "int"),
	MES_TYPED(913, false, false, false, new String[]{"i", "i", "s"}, null),
	INSTR6239(172, false, false, true, null, null),
	INSTR6148(137, false, false, false, null, "int"),
	INV_GETNUM(138, false, false, false, new String[]{"i", "i"}, "int"),
	CC_SETSIZE(140, false, false, false, new String[]{"i", "i", "i", "i"}, null),
	INSTR6704(141, false, false, false, null, "int"),
	ENUM_GETREVERSECOUNT(149, false, false, false, new String[]{"i", "i", "i"}, "int"),
	CHAR_ISALPHANUMERIC(150, false, false, false, new String[]{"i"}, "int"),
	ACTIVECLANSETTINGS_GETAFFINEDRANK(166, false, false, false, new String[]{"i"}, "int"),
	CC_ISHIDDEN(747, false, false, false, null, "int"),
	FC_GETCHATDISPLAYNAME(765, false, false, false, null, "string"),
	ITEM_FINDNEXT(623, false, false, false, null, "int"),
	INSTR6583(328, false, false, false, new String[]{"i"}, "string"),
	FC_GETCHATCOUNT(1002, false, false, false, null, "int"),
	ITEM_FIND(800, false, false, false, new String[]{"s", "i"}, "int"),
	INSTR6141(936, false, false, false, null, "int,int"),
	INSTR6790(607, false, false, false, new String[]{"i", "i"}, null),
	INSTR6088(813, false, false, false, null, null),
	ACTIVECLANCHANNEL_GETCLANNAME(370, false, false, false, null, "string"),
	REMOVETAGS(41, false, false, false, new String[]{"s"}, "string"),
	INSTR6666(110, false, false, false, new String[]{"i", "i"}, null),
	IF_GETY(170, false, false, false, new String[]{"ic"}, "int"),
	IGNORE_ADD(177, false, false, false, new String[]{"s"}, null),
	MODULO(178, false, false, false, new String[]{"i", "i"}, "int", MathsInstruction.class),
	INV_GETITEM(180, false, false, false, new String[]{"i", "i"}, "int"),
	FRIEND_COUNT(183, false, false, false, null, "int"),
	USERDETAIL_QUICKCHAT(201, false, false, false, null, "int"),
	WORLD_LANGUAGE(202, false, false, false, null, "int"),
	CC_GETPARENT(204, false, false, false, null, "int"),
	IF_SET2DANGLE(205, false, false, false, new String[]{"ic", "i"}, null),
	RESUME_NAMEDIALOG(216, false, false, false, new String[]{"s"}, null),
	INSTR6075(223, false, false, false, new String[]{"i"}, null),
	IF_SETCLICKMASK(224, false, false, false, new String[]{"i", "i"}, null),
	CHAT_GETMESSAGE(231, false, false, false, new String[]{"i"}, "string"),
	INSTR6213(255, false, false, false, new String[]{"ic", "i", "s"}, null),
	POP_2_INT(65, false, false, false, null, null),
	SEND_PRIVATE_MESSAGE(743, false, false, false, new String[]{"s", "s"}, null),
	DETAILSET_CUSTOMCURSOR(181, false, false, false, new String[]{"i"}, null),
	RANDOM(675, false, false, false, new String[]{"i"}, "int"),
	COMLEVEL_ACTIVE(139, false, false, false, null, "int"),
	COORD(389, false, false, false, null, "int"),
	INSTR6255(630, false, false, true, null, null),
	INSTR6237_1(244, false, false, true, null, null),
	INSTR6652(595, false, false, false, new String[]{"i"}, "int"),
	RUNENERGY_VISIBLE_1(944, false, false, false, null, "int"),
	IF_SETNPCHEAD(857, false, false, false, new String[]{"i", "ic"}, null),
	RANDOM_SOUND_PITCH(729, false, false, false, new String[]{"i", "i"}, "int"),
	IF_SETNOCLICKTHROUGH(668, false, false, false, new String[]{"i", "i"}, null),
	OPPLAYER(162, false, false, false, new String[]{"i", "s"}, null),
	SOUND_VORBIS_VOLUME(516, false, false, false, new String[]{"i", "i", "i", "i"}, null),
	INSTR6237_2(244, false, false, true, null, null),
	IF_SETONMOUSELEAVE_1(809, false, false, true, null, null),
	INSTR6556(957, false, false, false, null, null),
	INSTR6771(832, false, true, false, null, null),
	INSTR6677(107, false, false, false, new String[]{"i", "i", "i", "i", "i", "i"}, null),
	INSTR6236(396, false, false, false, null, null),
	ITEM_PARAM(120, false, true, false, null, null),
	IF_SETMODELTINT(82, false, false, false, new String[]{"i", "i", "i", "i"}, null),
	CC_DRAGPICKUP(259, false, false, false, new String[]{"i", "i"}, null),
	IF_GETWIDTH(263, false, false, false, new String[]{"ic"}, "int", SimpleInstruction.class),
	CC_SETCOLOR(274, false, false, false, new String[]{"i"}, null),
	CC_SETOPBASE(275, false, false, false, new String[]{"s"}, null),
	BIT_FLAGGED(278, false, false, false, new String[]{"i", "i"}, "int"),
	TOSTRING_LOCALIZED(280, false, false, false, new String[]{"i", "i"}, "string"),
	APPEND(286, false, false, false, new String[]{"s", "s"}, "string", CustomInstruction.class),
	ITEM_USEONNAME(289, false, false, false, new String[]{"i", "s"}, null),
	CHAT_PLAYERNAME(292, false, false, false, null, "string"),
	FC_JOINCHAT(293, false, false, false, new String[]{"s"}, null, SimpleInstruction.class),
	INSTR6507(768, false, false, true, null, null),
	INSTR6251(416, false, false, true, null, null),
	STORE_VARP(929, true, false, false, null, null, StoreVarInstruction.class),
	CC_SETMODELORTHOG(363, false, false, false, new String[]{"i"}, null),
	CHAT_GETCLAN(622, false, false, false, new String[]{"i"}, "string"),
	INSTR6231(143, false, false, true, null, null),
	BIT_AND(199, false, false, false, null, null, MathsInstruction.class),
	NPC_PARAM(425, false, false, false, null, null),
	BIT_OR(474, false, false, false, null, null, MathsInstruction.class),
	INSTR6103(991, false, false, false, null, null),
	BIT_NOT(534, false, false, false, null, null, MathsInstruction.class),
	PLAYERMEMBER(262, false, false, false, null, "int"),
	CC_SETMODELANIM(32, false, false, false, new String[]{"i"}, null),
	INSTR6714(666, false, false, false, null, "int,int,int"),
	INSTR6116(70, false, false, false, null, null),
	INSTR6802(256, false, false, false, new String[]{"i"}, "int"),
	CC_SETSCROLLPOS(126, false, false, false, new String[]{"i", "i"}, null),
	ACTIVECLANCHANNEL_GETRANKTALK(489, false, false, false, null, "int"),
	INSTR6710(447, false, false, false, null, "int"),
	WORLD_ID(601, false, false, false, null, "int"),
	INSTR6717(509, false, false, false, null, null),
	INSTR6694(171, false, false, false, null, null),
	GET_MOUSEBUTTONS(453, false, false, false, null, "int,int,int"),
	CC_SETSCROLLSIZE(28, false, false, false, new String[]{"i", "i"}, null),
	CC_SETASPECT(341, false, false, false, new String[]{"i", "i"}, null),
	PLAYERMODLEVEL(718, false, false, false, null, "int"),
	CC_GETTRANSPARENCY(34, false, false, false, null, "int"),
	CC_GETSPRITEYAW(648, false, false, false, null, "int"),
	RUNENERGY_VISIBLE_2(944, false, false, false, null, "int"),
	RUNWEIGHT_VISIBLE(866, false, false, false, null, "int"),
	CC_GETOPTIONFLAGS(467, false, false, false, null, "int"),
	IF_ISOPENWITHID(448, false, false, false, new String[]{"i", "i"}, "int"),
	IF_ISOPENWITHID2(331, false, false, false, new String[]{"i", "i"}, "int"),
	IF_SETSPRITESHADOW(131, false, false, false, new String[]{"ic", "i"}, null),
	CC_SENDTOFRONT(993, false, false, false, null, null),
	INSTR6686(155, false, false, false, new String[]{"i"}, null),
	STOCKMARKET_GETOFFERTYPE(414, false, false, false, new String[]{"i"}, "int"),
	INSTR6096(315, false, false, false, null, null),
	IF_SETOPTIONNAME(790, false, false, false, new String[]{"ic", "s"}, null),
	MOVECOORD(48, false, false, false, new String[]{"i", "i", "i", "i"}, "int"),
	ITEM_STACKABLE(905, false, false, false, new String[]{"i"}, "int"),
	LOBBY_CLICKHYPERLINK(343, false, false, false, new String[]{"s", "s", "s", "i"}, null),
	DETAILGET_SOUNDEFFECT_VOLUME(828, false, false, false, null, "int"),
	DETAILSET_BGSOUNDVOL(417, false, false, false, new String[]{"i"}, null),
	CC_SETOPCURSOR(176, false, false, false, new String[]{"i", "i"}, null),
	RESUME_ITEMDIALOG(304, false, false, false, new String[]{"i"}, null),
	INSTR6235(478, false, false, true, null, null),
	INSTR6240(926, false, false, true, null, null),
	GET_ENTITY_BOUNDING_BOX(95, false, false, false, null, "int,int,int,int,int"),
	GET_OBJECT_BOUNDING_BOX(69, false, false, false, null, "int,int,int,int,int"),
	GET_ITEM_BOUNDING_BOX(517, false, false, false, null, "int,int,int,int,int"),
	INSTR6215(495, false, false, false, new String[]{"i"}, null),
	INSTR6655(355, false, false, false, new String[]{"s", "i"}, null),
	IF_SETFILL(918, false, false, false, new String[]{"ic", "i"}, null),
	GET_ACTIVE_MINIMENU_ENTRY(115, false, false, false, null, "int,string,string,string"),
	LOAD_CLAN_VAR(717, true, false, false, null, null, LoadVarInstruction.class),
	LOAD_CLAN_SETTING_VAR(73, true, false, false, null, null, LoadVarInstruction.class),
	INSTR6260(401, false, false, true, null, null),
	IF_GETCOLOR(798, false, false, false, new String[]{"ic"}, "int"),
	GET_MINIMENU_TARGET(814, false, false, false, null, "int,string,string"),
	RESUME_HSLDIALOG(238, false, false, false, new String[]{"i"}, null),
	HSVTORGB(586, false, false, false, new String[]{"i"}, "int"),
	CC_CLEARSCRIPTS(702, false, false, false, null, null),
	ACTIVECLANSETTINGS_FIND_LISTENED(833, false, false, false, null, "int"),
	TEXT_SWITCH(15, false, false, false, new String[]{"s", "s"}, "string"),
	APPEND_SIGNNUM(573, false, false, false, new String[]{"s", "i"}, "string"),
	INSTR6218(627, false, false, false, new String[]{"i", "i"}, null),
	GET_MINIMENU_LENGTH(50, false, false, false, null, "int,int"),
	GET_MOUSE_X(243, false, false, false, null, "int"),
	GET_MOUSE_Y(308, false, false, false, null, "int"),
	CC_SETTEXTANTIMACRO(644, false, false, false, new String[]{"i"}, null),
	GET_ENTITY_SCREEN_POSITION(330, false, false, false, new String[]{"i"}, "int,int,int"),
	GET_OBJECT_SCREEN_POSITION(439, false, false, false, new String[]{"i"}, "int,int,int"),
	GET_ITEM_SCREEN_POSITION(450, false, false, false, new String[]{"i"}, "int,int,int"),
	EMAIL_VALIDATION_CHANGE_ADDRESS(121, false, false, false, new String[]{"s", "s"}, null),
	INSTR6623(242, false, false, false, null, null),
	INSTR6629(455, false, false, false, new String[]{"i"}, null),
	GET_CURRENTCURSOR(980, false, false, false, null, "int"),
	INSTR6721(357, false, false, false, null, "string"),
	INSTR6911(669, false, false, false, null, "int"),
	GET_OBJECT_OVERLAY_HEIGHT(433, false, false, false, null, "int"),
	GET_ITEM_OVERLAY_HEIGHT(295, false, false, false, null, "int"),
	EMAIL_VALIDATION_SUBMIT_CODE(364, false, false, false, new String[]{"s"}, null),
	IF_GETCONTAINERITEMID(808, false, false, false, new String[]{"ic"}, "int"),
	INSTR6703(498, false, false, false, null, "int"),
	INSTR6698(684, false, false, false, new String[]{"i"}, null),
	INSTR6365(55, false, false, false, null, "int"),
	CC_GETSCROLLY(755, false, false, false, null, "int"),
	DETAILSET_MUSICVOL(276, false, false, false, new String[]{"i"}, null),
	DETAILSET_VOICEOVERVOLUME(632, false, false, false, new String[]{"i"}, null),
	CC_SETLINEDIRECTION(965, false, false, false, new String[]{"i"}, null),
	CC_GETOFFSETX(97, false, false, false, null, "int"),
	CC_GETOFFSETY(728, false, false, false, null, "int"),
	CC_SETLINEWIDTH(124, false, false, false, new String[]{"i"}, null),
	CC_GETSPRITEROLL(555, false, false, false, null, "int"),
	CC_SETMODELZOOM(159, false, false, false, new String[]{"i"}, null),
	CC_SET2DANGLE(196, false, false, false, new String[]{"i"}, null),
	BAS_GETANIM_READY(456, false, false, false, new String[]{"i"}, "int"),
	CC_GETPARENTLAYER(626, false, false, false, null, "int"),
	STOCKMARKET_ISOFFERADDING(361, false, false, false, new String[]{"i"}, "int"),
	STOCKMARKET_GETOFFERITEM(602, false, false, false, new String[]{"i"}, "int"),
	STOCKMARKET_ISOFFERFINISHED(984, false, false, false, new String[]{"i"}, "int"),
	STOCKMARKET_GETOFFERCOUNT(27, false, false, false, new String[]{"i"}, "int"),
	STOCKMARKET_GETOFFERPRICE(575, false, false, false, new String[]{"i"}, "int"),
	STOCKMARKET_GETOFFERCOMPLETEDCOUNT(480, false, false, false, new String[]{"i"}, "int"),
	CC_SETONMOUSELEAVE_1(191, false, false, false, null, null),
	INSTR6095(697, false, false, false, null, null),
	INSTR6899(886, false, false, false, null, null),
	INSTR6232(382, false, false, true, null, null),
	INSTR6254(947, false, false, true, null, null),
	INSTR6094(892, false, false, false, null, null),
	IF_GETSPRITEID(169, false, false, false, new String[]{"ic"}, "int"),
	STOCKMARKET_ISOFFEREMPTY(650, false, false, false, new String[]{"i"}, "int"),
	IF_CLEARSCRIPTHOOKS(64, false, false, false, new String[]{"ic"}, null),
	CC_SENDTOBACK(584, false, false, false, null, null),
	IF_SENDTOFRONT(515, false, false, false, new String[]{"ic"}, null),
	IF_SENDTOBACK(246, false, false, false, new String[]{"ic"}, null),
	DETAILGET_AMBIENTSOUND_VOLUME(919, false, false, false, null, "int"),
	CC_SETPLAYERMODEL_SELF(443, false, false, false, null, null),
	CC_SETITEM_ALWAYSNUM(998, false, false, false, new String[]{"i", "i"}, null),
	LOAD_CLAN_SETTING_VARBIT(147, true, false, false, null, null, LoadVarInstruction.class),
	INSTR6376(758, false, false, true, null, null),
	INSTR6898(105, false, false, true, null, null),
	LOAD_CLAN_VARBIT(220, true, false, false, null, null, LoadVarInstruction.class),
	INSTR6450(374, false, false, false, null, null),
	INSTR6527(770, false, false, true, null, null),
	WORLDLIST_SETWORLD(239, false, false, false, new String[]{"i", "s"}, "int"),
	WORLDLIST_GETINFO(960, false, false, false, new String[]{"i"}, "int,string,int,string,int,int,string"),
	STAT_VISIBLE_XP(772, false, false, false, new String[]{"i"}, "int"),
	DETAILSET_SOUNDVOL(358, false, false, false, new String[]{"i"}, null),
	INSTR6707(19, false, false, false, new String[]{"s", "s"}, null),
	SOUND_JINGLE(920, false, false, false, new String[]{"i", "i"}, null),
	IF_SETTILING(460, false, false, false, new String[]{"ic", "i"}, null),
	STOCKMARKET_GETOFFERCOMPLETEDGOLD(687, false, false, false, new String[]{"i"}, "int"),
	INSTR6641(182, false, false, false, null, null),
	ENUM_HASOUTPUT(60, false, false, false, new String[]{"i", "i", "i"}, "int"),
	CC_SETNOCLICKTHROUGH(787, false, false, false, new String[]{"i"}, null),
	INSTR6299(197, false, false, false, new String[]{"ic"}, null),
	APPLET_CALL(63, false, false, false, new String[]{"s"}, null),
	INSTR6783(353, false, false, false, null, "int"),
	INSTR6869(337, false, false, false, new String[]{"s"}, "int"),
	INSTR6261(111, false, false, true, null, null),
	INSTR6247(683, false, false, true, null, null),
	INSTR6250(625, false, false, true, null, null),
	ACTIVECLANCHANNEL_GETUSERWORLD(23, false, false, false, new String[]{"i"}, "int"),
	FC_GETCHATUSERNAME_UNFILTERED(580, false, false, false, new String[]{"i"}, "string"),
	INSTR6122(151, false, false, false, null, "int"),
	FROMDATE(618, false, false, false, new String[]{"i"}, "string"),
	IF_SETMOUSEOVERCURSOR(786, false, false, false, new String[]{"ic", "i"}, "int"),
	ACTIVECLANCHANNEL_GETUSERCOUNT(399, false, false, false, null, "int"),
	ACTIVECLANSETTINGS_GETBANNEDCOUNT(411, false, false, false, null, "int"),
	ACTIVECLANCHANNEL_GETUSERDISPLAYNAME(444, false, false, false, new String[]{"i"}, "string"),
	ACTIVECLANSETTINGS_GETRANKKICK(894, false, false, false, null, "int"),
	ACTIVECLANCHANNEL_KICKUSER(350, false, false, false, new String[]{"i"}, null),
	CC_GET2DANGLE(723, false, false, false, null, "int"),
	FC_GETCHATUSERRANK(394, false, false, false, new String[]{"i"}, "int"),
	CAM_GETANGLEX(493, false, false, false, null, "int"),
	ACTIVECLANCHANNEL_GETRANKKICK(907, false, false, false, null, "int"),
	INSTR6719(506, false, false, false, new String[]{"i"}, null),
	FC_LEAVECHAT(682, false, false, false, null, null),
	FC_GETCHATOWNERNAME(338, false, false, false, null, "string"),
	IF_CLOSESUBCLIENT(291, false, false, false, new String[]{"i"}, null),
	INSTR6708(76, false, false, true, null, null),
	ACTIVECLANSETTINGS_GETBANNEDDISPLAYNAME(746, false, false, false, new String[]{"i"}, "string"),
	INSTR6576(875, false, false, false, null, "int"),
	INSTR6774(551, false, false, false, null, "int"),
	CAM_GETANGLEY(161, false, false, false, null, "int"),
	CAM_SETANGLE(144, false, false, false, new String[]{"i", "i"}, null),
	CC_SETRETEX(579, false, false, false, new String[]{"i", "i", "i"}, null),
	DETAILGET_VOICEOVER_VOLUME(971, false, false, false, null, "int"),
	INSTR6868(420, false, false, false, new String[]{"s"}, "int"),
	IF_RESUME_PAUSEBUTTON(326, false, false, false, new String[]{"ic"}, null),
	ITEM_COST(89, false, false, false, new String[]{"i"}, "int"),
	CC_SETUSEOP(466, false, false, false, new String[]{"s"}, null),
	IF_RECOLOUR(194, false, false, false, new String[]{"ic", "i", "i", "i"}, null),
	IF_RETEXTURE(950, false, false, false, new String[]{"ic", "i", "i", "i"}, null),
	CC_GETSPRITEID(449, false, false, false, null, "int"),
	OC_ICURSOR(45, false, false, false, new String[]{"i", "i"}, "int"),
	INSTR6391(52, false, false, false, new String[]{"ic", "i"}, "int,int"),
	INSTR6300(163, false, false, false, new String[]{"ic", "i", "i"}, "int"),
	APPLET_HASFOCUS(781, false, false, false, null, "int"),
	EMAIL_VALIDATION_ADD_NEW_ADDRESS(511, false, false, false, new String[]{"s", "i", "i", "i"}, null),
	DETAILGET_MUSIC_VOLUME(942, false, false, false, null, "int"),
	INSTR6678(940, false, false, false, null, null),
	POW(645, false, false, false, null, null, MathsInstruction.class),
	POW_INVERSE(776, false, false, false, new String[]{"i", "i"}, "int"),
	CC_SETPLAYERHEAD_SELF(186, false, false, false, null, null),
	CC_RESETOPNAME(611, false, false, false, null, null),
	INSTR6765(615, false, false, false, null, null),
	COORDX(93, false, false, false, new String[]{"i"}, "int"),
	COORDY(298, false, false, false, new String[]{"i"}, "int"),
	COORDZ(536, false, false, false, new String[]{"i"}, "int"),
	CC_SETMODEL(872, false, false, false, new String[]{"i"}, null),
	INSTR6797(519, false, false, false, null, "int"),
	CC_SETOPNAME(806, false, false, false, new String[]{"s"}, null),
	CC_GETSPRITEPITCH(491, false, false, false, null, "int"),
	INSTR6257(189, false, false, true, null, null),
	CC_SETNPCHEAD(542, false, false, false, new String[]{"i"}, null),
	IF_CLOSE(574, false, false, false, null, null),
	PLAYERCOUNTRY(667, false, false, false, null, "int"),
	INSTR6256(321, false, false, true, null, null),
	SEND_PUBLIC_CHAT(134, false, false, false, new String[]{"s"}, null),
	IF_GETPARENTLAYER(692, false, false, false, new String[]{"i"}, "int"),
	CC_CONTAINERITEMID(36, false, false, false, null, "int"),
	CC_SETMODELANGLE(528, false, false, false, new String[]{"i", "i", "i", "i", "i", "i"}, null),
	CHATLINE_GETCYCLES20MS(272, false, false, false, new String[]{"i"}, "int"),
	WINDOWED_GETMODE(297, false, false, false, null, "int"),
	INSTR6342(300, false, false, true, null, null),
	STAT(301, false, false, false, new String[]{"i"}, "int", SimpleInstruction.class),
	GET_DISPLAYNAME(309, false, false, false, null, "string"),
	ITEM_UNCERT(313, false, false, false, new String[]{"i"}, "int"),
	CC_SETOUTLINE(317, false, false, false, new String[]{"i"}, null),
	INSTR6004(333, false, false, false, new String[]{"ic"}, "int"),
	INSTR6606(334, false, false, false, null, "int"),
	CHAT_QUICKCHATID(335, false, false, false, new String[]{"i"}, "int"),
	WORLD_MEMBERS(336, false, false, false, null, "int", SimpleInstruction.class),
	STAT_BASE(340, false, false, false, new String[]{"i"}, "int", SimpleInstruction.class),
	IF_SETBORDERTHICKNESS(344, false, false, false, new String[]{"i", "i"}, null, SimpleInstruction.class),
	INSTR6073(345, false, false, false, new String[]{"i"}, null),
	ACTIVECLANCHANNEL_FIND_AFFINED(347, false, false, false, null, "int"),
	CC_SETTEXTFONT(351, false, false, false, new String[]{"i"}, null),
	IF_SETPARAM_INT(369, false, false, false, new String[]{"ic", "i", "i"}, null),
	ITEM_NAME(385, false, false, false, new String[]{"i"}, "string"),
	SOUND_VORBIS_RATE(395, false, false, false, new String[]{"i", "i", "i", "i", "i"}, null),
	CC_SETFILL(402, false, false, false, new String[]{"i"}, null),
	CC_SETTILING(406, false, false, false, new String[]{"i"}, null),
	CC_SETITEM_NONUM(412, false, false, false, new String[]{"i", "i"}, null),
	WORLD_ISQUICKCHAT(427, false, false, false, null, "int"),
	IF_GETSCROLLY(428, false, false, false, new String[]{"i"}, "int"),
	INSTR6280(436, false, false, false, new String[]{"ic"}, "int"),
	ACTIVECLANSETTINGS_FIND_AFFINED(452, false, false, false, null, "int"),
	STRINGWIDTH(459, false, false, false, new String[]{"i", "s"}, "int"),
	INSTR6292(461, false, false, false, new String[]{"ic"}, "int"),
	INSTR6573(462, false, false, false, new String[]{"i"}, "string"),
	IF_SETMODEL(488, false, false, false, new String[]{"ic", "i"}, null),
	CC_SETPARAM_INT(497, false, false, false, new String[]{"i", "i"}, null),
	INSTR6220(512, false, false, false, new String[]{"ic"}, null),
	FRIEND_GETSLOTFROMNAME(520, false, false, false, new String[]{"s"}, "int"),
	USERDETAIL_LOBBY_GRACEEXPIRY(522, false, false, false, null, "int"),
	CC_GETY(523, false, false, false, null, "int"),
	ENUM_GETOUTPUTCOUNT(533, false, false, false, new String[]{"i"}, "int"),
	INSTR6289(543, false, false, false, new String[]{"ic"}, "int"),
	CC_GETWIDTH(545, false, false, false, null, "int"),
	CC_SETTEXTALIGN(546, false, false, false, new String[]{"i", "i", "i"}, null),
	INSTR6129(552, false, false, false, new String[]{"i", "i", "i"}, null),
	LOWER_STRING(556, false, false, false, new String[]{"s"}, "string", CustomInstruction.class),
	ACTIVECLANSETTINGS_GETAFFINEDSLOT(557, false, false, false, new String[]{"s"}, "int"),
	CLAN_VARS_ENABLED(559, false, false, false, null, "int"),
	IF_GETHIDE(578, false, false, false, new String[]{"ic"}, "int"),
	STRING_INDEXOF_CHAR(593, false, false, false, new String[]{"s", "i", "i"}, "int"),
	CC_SETVFLIP(599, false, false, false, new String[]{"i"}, null),
	HOOK_MOUSE_EXIT(600, false, false, true, null, null),
	IF_SETMODELANGLE(605, false, false, false, new String[]{"ic", "i", "i", "i", "i", "i", "i"}, null),
	FRIEND_ADD(609, false, false, false, new String[]{"s"}, null),
	INVOTHER_GETITEM(612, false, false, false, new String[]{"i", "i"}, "int"),
	INSTR6151(620, false, false, false, null, "int"),
	INSTR6072(624, false, false, false, new String[]{"ic"}, "int"),
	CHAR_ISPRINTABLE(638, false, false, false, new String[]{"i"}, "int"),
	CC_SETPARAM_STRING(639, false, false, false, new String[]{"i", "s"}, null),
	INSTR6180(651, false, false, false, new String[]{"i", "i"}, null),
	GENDER(657, false, false, false, null, "int"),
	CC_SETOP(671, false, false, false, new String[]{"s", "i"}, null),
	ACTIVECLANCHANNEL_GETUSERRANK(673, false, false, false, new String[]{"i"}, "int"),
	CC_FIND(677, false, false, false, new String[]{"i", "ic"}, "int", SimpleInstruction.class),
	CHATLINE_GETTYPE(681, false, false, false, new String[]{"i"}, "int"),
	IF_SETTEXTSHADOW(689, false, false, false, new String[]{"ic", "i"}, null),
	IF_SETMODELANIM(690, false, false, false, new String[]{"ic", "i"}, null, SimpleInstruction.class),
	APPEND_CHAR(701, false, false, false, new String[]{"s", "i"}, "string"),
	INSTR6296(704, false, false, false, new String[]{"ic"}, "int", SimpleInstruction.class),
	IF_GETX(710, false, false, false, new String[]{"ic"}, "int"),
	GET_SYSTEM_UPDATE_TIMER(715, false, false, false, null, "int"),
	INVOTHER_GETNUM(720, false, false, false, new String[]{"i", "i"}, "int"),
	IF_SETTEXT(724, false, false, false, new String[]{"ic", "s"}, null, SimpleInstruction.class),
	STAFFMODLEVEL(727, false, false, false, null, "int"),
	IGNORE_COUNT(735, false, false, false, null, "int"),
	IF_GETTEXT(748, false, false, false, new String[]{"ic"}, "string", SimpleInstruction.class),
	CC_SETGRAPHICSHADOW(751, false, false, false, new String[]{"i"}, null),
	IF_SETTRANS(763, false, false, false, new String[]{"ic", "i"}, null, SimpleInstruction.class),
	INSTR6443(764, false, false, false, new String[]{"i"}, null),
	IF_SETHFLIP(774, false, false, false, new String[]{"ic", "i"}, null),
	CHAT_GETCROWNEDNAME(789, false, false, false, new String[]{"i"}, "string"),
	CHAT_GETFILTER_PRIVATE(792, false, false, false, null, "int"),
	CC_GETHEIGHT(796, false, false, false, null, "int"),
	CC_GETX(797, false, false, false, null, "int"),
	COMPARE(810, false, false, false, new String[]{"s", "s"}, "int", SimpleInstruction.class),
	IF_SETCOLOR(816, false, false, false, new String[]{"ic", "col"}, null, SimpleInstruction.class),
	ENUM_STRING(820, false, false, false, new String[]{"i", "i"}, "string"),
	ITEM_MEMBERS(822, false, false, false, new String[]{"i"}, "int", SimpleInstruction.class),
	IF_SETSCROLLPOS(825, false, false, false, new String[]{"ic", "i", "i"}, null),
	STRING_INDEXOF_STRING(844, false, false, false, new String[]{"s", "s", "i"}, "int"),
	CC_SETPOSITION(847, false, false, false, new String[]{"i", "i", "i", "i"}, null),
	IGNORE_DEL(871, false, false, false, new String[]{"s"}, null),
	FRIEND_TEST(879, false, false, false, new String[]{"s"}, "int"),
	FRIEND_PLATFORM(880, false, false, false, new String[]{"i"}, "int"),
	ACTIVECLANCHANNEL_GETUSERSLOT(897, false, false, false, new String[]{"s"}, "int"),
	CC_GETSPRITESCALE(0, false, false, false, null, "int"),
	ENUM_GETREVERSEINDEX(904, false, false, false, new String[]{"i", "i", "i", "i", "i"}, "int"),
	IF_GETTRANS(912, false, false, false, new String[]{"ic"}, "int"),
	FRIEND_DEL(914, false, false, false, new String[]{"s"}, null),
	CHAR_ISNUMERIC(934, false, false, false, new String[]{"i"}, "int"),
	ITEM_IOP(949, false, false, false, new String[]{"i", "i"}, "string"),
	IF_GETHEIGHT(953, false, false, false, new String[]{"ic"}, "int"),
	INSTR6584(958, false, false, false, new String[]{"i"}, "int"),
	IGNORE_TEST(966, false, false, false, new String[]{"s"}, "int"),
	HOOK_MOUSE_ENTER(968, false, false, true, null, null),
	CC_SETTEXT(972, false, false, false, new String[]{"s"}, null),
	IF_GETSCROLLHEIGHT(978, false, false, false, new String[]{"i"}, "int"),
	CC_GETTEXT(979, false, false, false, null, "string"),
	IF_GETNEXTSUBID(1000, false, false, false, new String[]{"ic"}, "int");

	private final int opcode;
	private final boolean hasExtra;
	private final boolean hasExtraValue;
	private final boolean hasExtraHook;
	private final String[] arguments;
	private final String returnType;
	private final Class<? extends Instruction> clazz;

	private static HashMap<String, InstructionDefinitions> byNameMap = new HashMap<>();
	private static HashMap<Integer, InstructionDefinitions> byOpcodeMap = new HashMap<>();

	static {
		for (InstructionDefinitions instruction : values())
			byNameMap.put(instruction.name().toLowerCase(), instruction);
		for (InstructionDefinitions instruction : values())
			byOpcodeMap.put(instruction.getOpcode(), instruction);
	}

	InstructionDefinitions(int opcode, boolean hasExtra, boolean hasExtraValue, boolean hasExtraHook, String[] arguments, String returnType) {
		this(opcode, hasExtra, hasExtraValue, hasExtraHook, arguments, returnType, null);
	}

	InstructionDefinitions(int opcode, boolean hasExtra, boolean hasExtraValue, boolean hasExtraHook, String[] arguments, String returnType, Class<? extends Instruction> clazz) {
		this.opcode = opcode;
		this.hasExtra = hasExtra;
		this.hasExtraValue = hasExtraValue;
		this.hasExtraHook = hasExtraHook;
		this.arguments = arguments;
		this.returnType = returnType;
		this.clazz = clazz;
	}

	public int getOpcode() {
		return opcode;
	}

	public boolean hasExtra() {
		return hasExtra;
	}

	public boolean hasExtraValue() {
		return hasExtraValue;
	}

	public boolean hasExtraHook() {
		return hasExtraHook;
	}

	public String[] getArguments() {
		return arguments;
	}

	public String getReturnType() {
		return returnType;
	}

	public Class<? extends Instruction> getClazz() {
		return clazz;
	}

	public static InstructionDefinitions getByOpcode(int opcode) {
		return byOpcodeMap.get(opcode);
	}

	public static InstructionDefinitions getByName(String name) {
		return byNameMap.get(name);
	}
}
